In [1]:
pip install duckdb

Collecting duckdb
  Downloading duckdb-1.5.0-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.0-cp313-cp313-win_amd64.whl (13.1 MB)
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   -- ------------------------------------- 0.8/13.1 MB 7.0 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/13.1 MB 3.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/13.1 MB 2.3 MB/s eta 0:00:06
   ---- ----------------------------------- 1.6/13.1 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/13.1 MB 1.8 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/13.1 MB 1.7 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/13.1 MB 1.6 MB/s eta 0:00:07
   -------- ------------------------------- 2.9/13.1 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 3.1/13.1 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/13.1 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/13.1 MB 1.5 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/13.1 MB 1.4 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/13.1 MB 1.4 MB/s eta 0:00:07
   ------------ --------------------------- 3.9/13.1 MB 1.3 MB/s eta 0:00:08
   ------------- -------------------------- 4.5/13.1 MB 1.3 MB/s eta 0:00:07
   --------------- ------------------------ 5.0/13.1 MB 1.4 MB/s eta 0:00:06
   --------------- ------------------------ 5.0/13.1 MB 1.4 MB/s eta 0:00:06
   ---------------- ----------------------- 5.2/13.1 MB 1.3 MB/s eta 0:00:06
   ---------------- ----------------------- 5.5/13.1 MB 1.3 MB/s eta 0:00:06
   ----------------- ---------------------- 5.8/13.1 MB 1.3 MB/s eta 0:00:06
   ------------------ --------------------- 6.0/13.1 MB 1.3 MB/s eta 0:00:06
   ------------------- -------------------- 6.3/13.1 MB 1.3 MB/s eta 0:00:06
   -------------------- ------------------- 6.6/13.1 MB 1.3 MB/s eta 0:00:05
   -------------------- ------------------- 6.8/13.1 MB 1.3 MB/s eta 0:00:05
   --------------------- ------------------ 7.1/13.1 MB 1.3 MB/s eta 0:00:05
   ---------------------- ----------------- 7.3/13.1 MB 1.3 MB/s eta 0:00:05
   ------------------------ --------------- 7.9/13.1 MB 1.3 MB/s eta 0:00:04
   ------------------------ --------------- 8.1/13.1 MB 1.3 MB/s eta 0:00:04
   ------------------------- -------------- 8.4/13.1 MB 1.3 MB/s eta 0:00:04
   -------------------------- ------------- 8.7/13.1 MB 1.3 MB/s eta 0:00:04
   --------------------------- ------------ 8.9/13.1 MB 1.3 MB/s eta 0:00:04
   ---------------------------- ----------- 9.2/13.1 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 9.4/13.1 MB 1.3 MB/s eta 0:00:03
   ----------------------------- ---------- 9.7/13.1 MB 1.3 MB/s eta 0:00:03
   ------------------------------ --------- 10.0/13.1 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 10.2/13.1 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 10.2/13.1 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 10.5/13.1 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 10.7/13.1 MB 1.3 MB/s eta 0:00:02
   ---------------------------------- ----- 11.3/13.1 MB 1.3 MB/s eta 0:00:02
   ----------------------------------- ---- 11.5/13.1 MB 1.3 MB/s eta 0:00:02
   ------------------------------------ --- 11.8/13.1 MB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 12.1/13.1 MB 1.3 MB/s eta 0:00:01
   ------------------------------------- -- 12.3/13.1 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 12.6/13.1 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  12.8/13.1 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 13.1/13.1 MB 1.3 MB/s eta 0:00:00
Installing collected packages: duckdb
Successfully installed duckdb-1.5.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import duckdb

In [6]:
cursor = duckdb.connect()

### Loading Customer Table.

In [9]:
cursor.execute("SELECT * FROM read_csv_auto('D:/Module2/customers.csv')").df()

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\Predun\AppData\Local\Temp\ipykernel_15584\299965239.py:1: SyntaxWarning: invalid escape sequence '\M'
  cursor.execute("SELECT * FROM read_csv_auto('D:\Module2\customers.csv')").df()

   customer_id           name       city signup_date               email
0      CUST001     Rohan Iyer    Kolkata  2023-04-16   user1@example.com
1      CUST002    Aditya Shah     Mumbai  2022-06-11   user2@example.com
2      CUST003    Arjun Singh       Pune  2023-03-15   user3@example.com
3      CUST004     Neha Joshi     Mumbai  2022-11-06   user4@example.com
4      CUST005    Divya Joshi     Mumbai  2023-11-02   user5@example.com
5      CUST006    Neha Sharma    Chennai  2023-01-16   user6@example.com
6      CUST007      Pooja Rao    Chennai  2023-10-03   user7@example.com
7      CUST008      Amit Iyer     Mumbai  2023-11-03   user8@example.com
8      CUST009     Riya Verma      Delhi  2022-08-07   user9@example.com
9      CUST010    Kavya Menon       Pune  2023-08-31  user10@example.com
10     CUST011    Rohan Mehta       Pune  2023-04-01  user11@example.com
11     CUST012    Sneha Patel       Pune  2022-12-18  user12@example.com
12     CUST013     Riya Verma      Delhi  2022-05-16  user13@example.com
13     CUST014      Amit Iyer     Mumbai  2023-01-28  user14@example.com
14     CUST015    Divya Desai      Delhi  2022-11-17  user15@example.com
15     CUST016   Vikram Singh     Mumbai  2023-01-27  user16@example.com
16     CUST017   Nikhil Mehta  Hyderabad  2023-06-28  user17@example.com
17     CUST018      Neha Shah  Bangalore  2023-10-28  user18@example.com
18     CUST019   Vikram Patel  Hyderabad  2022-08-07  user19@example.com
19     CUST020    Arjun Verma     Mumbai  2023-03-30  user20@example.com
20     CUST021   Sneha Chopra       Pune  2022-05-24  user21@example.com
21     CUST022    Divya Patel  Bangalore  2023-01-29  user22@example.com
22     CUST023    Kavya Joshi       Pune  2022-05-24  user23@example.com
23     CUST024   Kavya Tiwari  Hyderabad  2022-03-28  user24@example.com
24     CUST025    Aarav Desai    Kolkata  2023-09-07  user25@example.com
25     CUST026     Pooja Nair  Hyderabad  2022-01-28  user26@example.com
26     CUST027    Suresh Nair       Pune  2023-09-14  user27@example.com
27     CUST028   Pooja Sharma    Kolkata  2023-02-06  user28@example.com
28     CUST029     Riya Reddy     Mumbai  2022-09-03  user29@example.com
29     CUST030       Riya Das     Mumbai  2022-09-04  user30@example.com
30     CUST031   Rohan Pillai  Bangalore  2023-06-25  user31@example.com
31     CUST032   Kiran Chopra    Chennai  2022-05-16  user32@example.com
32     CUST033  Lakshmi Gupta    Kolkata  2023-01-10  user33@example.com
33     CUST034     Amit Mehta  Hyderabad  2023-04-28  user34@example.com
34     CUST035    Rohan Joshi      Delhi  2022-03-11  user35@example.com
35     CUST036    Priya Reddy  Hyderabad  2022-02-10  user36@example.com
36     CUST037   Suresh Patel    Chennai  2022-10-21  user37@example.com
37     CUST038    Amit Tiwari  Hyderabad  2023-02-16  user38@example.com
38     CUST039   Vikram Joshi     Mumbai  2023-09-23  user39@example.com
39     CUST040     Amit Menon      Delhi  2022-11-14  user40@example.com
40     CUST041  Lakshmi Kumar    Chennai  2022-06-09  user41@example.com
41     CUST042     Amit Desai       Pune  2023-08-24  user42@example.com
42     CUST043   Kavya Sharma      Delhi  2023-03-24  user43@example.com
43     CUST044     Meera Iyer    Chennai  2022-03-30  user44@example.com
44     CUST045   Aarav Sharma  Bangalore  2023-09-19  user45@example.com
45     CUST046      Neha Iyer     Mumbai  2023-11-14  user46@example.com
46     CUST047    Rohan Gupta    Chennai  2022-05-21  user47@example.com
47     CUST048   Suresh Menon    Kolkata  2022-12-22  user48@example.com
48     CUST049    Neha Pillai      Delhi  2022-09-23  user49@example.com
49     CUST050    Sneha Mehta  Bangalore  2022-10-03  user50@example.com

### Loading Orders Table.

In [10]:
cursor.execute("SELECT * FROM read_json_auto('D:/Module2/orders.json')").df()

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\Predun\AppData\Local\Temp\ipykernel_15584\25554651.py:1: SyntaxWarning: invalid escape sequence '\M'
  cursor.execute("SELECT * FROM read_json_auto('D:\Module2\orders.json')").df()

   order_id customer_id order_date      status  total_amount  num_items
0   ORD2001     CUST028 2023-05-20   delivered          2397          1
1   ORD2002     CUST032 2023-08-22   delivered          6197          3
2   ORD2003     CUST037 2023-12-12   delivered          9897          1
3   ORD2004     CUST003 2023-01-07     shipped          5596          2
4   ORD2005     CUST012 2023-01-19  processing         15792          4
..      ...         ...        ...         ...           ...        ...
95  ORD2096     CUST011 2023-02-03   cancelled          1598          1
96  ORD2097     CUST047 2023-09-24     shipped          3497          3
97  ORD2098     CUST026 2023-01-10   delivered          4649          2
98  ORD2099     CUST038 2023-09-16   delivered          6294          2
99  ORD2100     CUST025 2023-11-24   delivered         21093          3

[100 rows x 6 columns]

### Loading Products table.

In [40]:
cursor.execute("SELECT * FROM 'D:/Module2/products.parquet'").df()

,line_item_id,order_id,product_id,product_name,category,quantity,unit_price,total_price
0,LI0001,ORD2007,PR02,Cotton Kurti,Clothing,4,899,3596
1,LI0002,ORD2057,PR07,Yoga Mat,Sports,1,699,699
2,LI0003,ORD2071,PR05,Python Book,Books,4,799,3196
3,LI0004,ORD2090,PR03,Basmati Rice 5kg,Grocery,2,450,900
4,LI0005,ORD2089,PR01,Wireless Earbuds,Electronics,3,2499,7497
...,...,...,...,...,...,...,...,...
95,LI0096,ORD2018,PR07,Yoga Mat,Sports,5,699,3495
96,LI0097,ORD2090,PR09,Mechanical Keyboard,Electronics,3,4599,13797
97,LI0098,ORD2090,PR09,Mechanical Keyboard,Electronics,3,4599,13797
98,LI0099,ORD2092,PR09,Mechanical Keyboard,Electronics,2,4599,9198
99,LI0100,ORD2026,PR04,Running Shoes,Footwear,5,3299,16495

### Creating Customers Table.

In [39]:
cursor.execute ("CREATE TABLE customers AS SELECT * FROM read_csv_auto('D:/Module2/customers.csv')")

CatalogException: Catalog Error: Table with name "customers" already exists!

In [18]:
cursor.execute("SELECT * FROM customers").fetchdf()

   customer_id           name       city signup_date               email
0      CUST001     Rohan Iyer    Kolkata  2023-04-16   user1@example.com
1      CUST002    Aditya Shah     Mumbai  2022-06-11   user2@example.com
2      CUST003    Arjun Singh       Pune  2023-03-15   user3@example.com
3      CUST004     Neha Joshi     Mumbai  2022-11-06   user4@example.com
4      CUST005    Divya Joshi     Mumbai  2023-11-02   user5@example.com
5      CUST006    Neha Sharma    Chennai  2023-01-16   user6@example.com
6      CUST007      Pooja Rao    Chennai  2023-10-03   user7@example.com
7      CUST008      Amit Iyer     Mumbai  2023-11-03   user8@example.com
8      CUST009     Riya Verma      Delhi  2022-08-07   user9@example.com
9      CUST010    Kavya Menon       Pune  2023-08-31  user10@example.com
10     CUST011    Rohan Mehta       Pune  2023-04-01  user11@example.com
11     CUST012    Sneha Patel       Pune  2022-12-18  user12@example.com
12     CUST013     Riya Verma      Delhi  2022-05-16  user13@example.com
13     CUST014      Amit Iyer     Mumbai  2023-01-28  user14@example.com
14     CUST015    Divya Desai      Delhi  2022-11-17  user15@example.com
15     CUST016   Vikram Singh     Mumbai  2023-01-27  user16@example.com
16     CUST017   Nikhil Mehta  Hyderabad  2023-06-28  user17@example.com
17     CUST018      Neha Shah  Bangalore  2023-10-28  user18@example.com
18     CUST019   Vikram Patel  Hyderabad  2022-08-07  user19@example.com
19     CUST020    Arjun Verma     Mumbai  2023-03-30  user20@example.com
20     CUST021   Sneha Chopra       Pune  2022-05-24  user21@example.com
21     CUST022    Divya Patel  Bangalore  2023-01-29  user22@example.com
22     CUST023    Kavya Joshi       Pune  2022-05-24  user23@example.com
23     CUST024   Kavya Tiwari  Hyderabad  2022-03-28  user24@example.com
24     CUST025    Aarav Desai    Kolkata  2023-09-07  user25@example.com
25     CUST026     Pooja Nair  Hyderabad  2022-01-28  user26@example.com
26     CUST027    Suresh Nair       Pune  2023-09-14  user27@example.com
27     CUST028   Pooja Sharma    Kolkata  2023-02-06  user28@example.com
28     CUST029     Riya Reddy     Mumbai  2022-09-03  user29@example.com
29     CUST030       Riya Das     Mumbai  2022-09-04  user30@example.com
30     CUST031   Rohan Pillai  Bangalore  2023-06-25  user31@example.com
31     CUST032   Kiran Chopra    Chennai  2022-05-16  user32@example.com
32     CUST033  Lakshmi Gupta    Kolkata  2023-01-10  user33@example.com
33     CUST034     Amit Mehta  Hyderabad  2023-04-28  user34@example.com
34     CUST035    Rohan Joshi      Delhi  2022-03-11  user35@example.com
35     CUST036    Priya Reddy  Hyderabad  2022-02-10  user36@example.com
36     CUST037   Suresh Patel    Chennai  2022-10-21  user37@example.com
37     CUST038    Amit Tiwari  Hyderabad  2023-02-16  user38@example.com
38     CUST039   Vikram Joshi     Mumbai  2023-09-23  user39@example.com
39     CUST040     Amit Menon      Delhi  2022-11-14  user40@example.com
40     CUST041  Lakshmi Kumar    Chennai  2022-06-09  user41@example.com
41     CUST042     Amit Desai       Pune  2023-08-24  user42@example.com
42     CUST043   Kavya Sharma      Delhi  2023-03-24  user43@example.com
43     CUST044     Meera Iyer    Chennai  2022-03-30  user44@example.com
44     CUST045   Aarav Sharma  Bangalore  2023-09-19  user45@example.com
45     CUST046      Neha Iyer     Mumbai  2023-11-14  user46@example.com
46     CUST047    Rohan Gupta    Chennai  2022-05-21  user47@example.com
47     CUST048   Suresh Menon    Kolkata  2022-12-22  user48@example.com
48     CUST049    Neha Pillai      Delhi  2022-09-23  user49@example.com
49     CUST050    Sneha Mehta  Bangalore  2022-10-03  user50@example.com

### Creating Orders Table.

In [20]:
cursor.execute ("CREATE TABLE orders AS SELECT * FROM read_json_auto('D:/Module2/orders.json')")

### Creating Products Table.

In [21]:
cursor.execute ("CREATE TABLE products AS SELECT * FROM 'D:/Module2/products.parquet'")

In [24]:
cursor.execute("SHOW TABLES").fetchall()

[('customers',), ('orders',), ('products',)]

### Checking the customer table's Column to make relationship.

In [25]:
cursor.execute("DESCRIBE customers").fetchdf()

   column_name column_type null   key default extra
0  customer_id     VARCHAR  YES  None    None  None
1         name     VARCHAR  YES  None    None  None
2         city     VARCHAR  YES  None    None  None
3  signup_date        DATE  YES  None    None  None
4        email     VARCHAR  YES  None    None  None

### Checking the Order table's Column to make relationship.

In [26]:
cursor.execute("DESCRIBE orders").fetchdf()

    column_name column_type null   key default extra
0      order_id     VARCHAR  YES  None    None  None
1   customer_id     VARCHAR  YES  None    None  None
2    order_date        DATE  YES  None    None  None
3        status     VARCHAR  YES  None    None  None
4  total_amount      BIGINT  YES  None    None  None
5     num_items      BIGINT  YES  None    None  None

### Checking the Product table's Column to make relationship.

In [27]:
cursor.execute("DESCRIBE products").fetchdf()

    column_name column_type null   key default extra
0  line_item_id     VARCHAR  YES  None    None  None
1      order_id     VARCHAR  YES  None    None  None
2    product_id     VARCHAR  YES  None    None  None
3  product_name     VARCHAR  YES  None    None  None
4      category     VARCHAR  YES  None    None  None
5      quantity      BIGINT  YES  None    None  None
6    unit_price      BIGINT  YES  None    None  None
7   total_price      BIGINT  YES  None    None  None

### Q1: List all customers along with the total number of orders they have placed.

In [29]:
cursor.execute("""
SELECT 
    c.name,
    COUNT(o.order_id) AS Total_orders
from customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
Group by c.name
""").fetchdf()

             name  Total_orders
0     Arjun Singh             2
1       Amit Iyer             4
2    Vikram Patel             2
3     Suresh Nair             1
4     Aditya Shah             3
5     Kavya Joshi             1
6    Sneha Chopra             1
7      Meera Iyer             1
8     Sneha Patel             4
9      Riya Reddy             1
10      Pooja Rao             1
11   Aarav Sharma             1
12   Suresh Patel             3
13     Riya Verma             3
14   Rohan Pillai             1
15    Divya Patel             0
16   Kavya Tiwari             0
17    Neha Sharma             4
18   Vikram Singh             4
19   Nikhil Mehta             3
20    Sneha Mehta             1
21      Neha Shah             2
22    Aarav Desai             4
23    Arjun Verma             3
24     Amit Mehta             0
25     Amit Menon             0
26    Divya Joshi             3
27     Amit Desai             3
28  Lakshmi Kumar             3
29    Divya Desai             0
30       Riya Das             0
31   Pooja Sharma             3
32     Pooja Nair             3
33   Suresh Menon             6
34      Neha Iyer             3
35     Neha Joshi             6
36    Amit Tiwari             3
37    Priya Reddy             1
38    Neha Pillai             0
39    Rohan Mehta             5
40   Vikram Joshi             1
41     Rohan Iyer             0
42   Kiran Chopra             4
43    Rohan Gupta             3
44    Rohan Joshi             1
45   Kavya Sharma             2
46    Kavya Menon             0
47  Lakshmi Gupta             0

### Q2: Find the top 3 customers by total order value.

In [30]:
cursor.execute("""
SELECT 
    c.name,
    SUM(o.total_amount) AS total_spent
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
GROUP BY  c.name
ORDER BY total_spent DESC
LIMIT 3
""").fetchdf()

           name  total_spent
0   Aarav Desai      50331.0
1    Neha Joshi      45527.0
2  Suresh Menon      40629.0

### Q3: List all products purchased by customers from Bangalore.

In [32]:
cursor.execute("""
SELECT 
    DISTINCT p.product_name
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
JOIN products p 
ON o.order_id = p.order_id
WHERE c.city = 'Bangalore'
""").fetchdf()

       product_name
0       Denim Jeans
1         Desk Lamp
2  Wireless Earbuds
3       Python Book
4      Cotton Kurti

### Q4: Join all three files to show: customer name, order date, product name, and quantity.

In [35]:
cursor.execute("""
SELECT 
    o.order_date,
    c.name AS customer_name,
    p.product_name,
    p.quantity
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
JOIN products p 
ON o.order_id = p.order_id
Order by o.order_date
""").fetchdf()

   order_date customer_name      product_name  quantity
0  2023-01-01   Rohan Gupta         Face Wash         5
1  2023-01-07   Arjun Singh  Basmati Rice 5kg         4
2  2023-01-10    Pooja Nair  Wireless Earbuds         1
3  2023-01-15   Amit Tiwari          Yoga Mat         3
4  2023-02-03   Rohan Mehta  Wireless Earbuds         1
..        ...           ...               ...       ...
95 2023-12-05  Kiran Chopra       Denim Jeans         4
96 2023-12-05  Kiran Chopra     Running Shoes         4
97 2023-12-17  Aarav Sharma  Wireless Earbuds         5
98 2023-12-21  Vikram Singh          Yoga Mat         2
99 2023-12-31   Neha Sharma  Wireless Earbuds         5

[100 rows x 4 columns]